name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    env:
      REACT_APP_PUBLIC_API_KEY: ${{ secrets.REACT_APP_PUBLIC_API_KEY }}
      REACT_APP_PUBLIC_AUTH_DOMAIN: ${{ secrets.REACT_APP_PUBLIC_AUTH_DOMAIN }}
      REACT_APP_PUBLIC_DB_URL: ${{ secrets.REACT_APP_PUBLIC_DB_URL }}
      REACT_APP_PUBLIC_PROJECT_ID: ${{ secrets.REACT_APP_PUBLIC_PROJECT_ID }}
      REACT_APP_PUBLIC_STORAGE_BUCKET: ${{ secrets.REACT_APP_PUBLIC_STORAGE_BUCKET }}
      REACT_APP_PUBLIC_MESSAGE_SENDER_ID: ${{ secrets.REACT_APP_PUBLIC_MESSAGE_SENDER_ID }}
      REACT_APP_PUBLIC_APP_ID: ${{ secrets.REACT_APP_PUBLIC_APP_ID }}
      REACT_APP_PUBLIC_MEASUREMENT_ID: ${{ secrets.REACT_APP_PUBLIC_MEASUREMENT_ID }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      # Build
      - run: npm i
      - run: npm run build
      # Deploy
      - uses: nekitcorp/yandex-storage-website-action@v2
        with:
          access-key-id: ${{ secrets.YANDEX_STATIC_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.YANDEX_STATIC_ACCESS_KEY_SECRET }}
          bucket: ${{ secrets.YANDEX_BUCKET }}
          working-directory: './dist'
          clear: false
